##################################################################################################################################
### Generate Image
###

### Test-Loop
GET https://m3sovazbdb.execute-api.eu-central-1.amazonaws.com/prod/?waitForSelector=body.renderingdone&url=https%3A//www.codeiris.com/dogecoin/dogecoin/view/latest%3Fcolor%3DIMPACT%26author%3Dlaanwj@gmail.com%26switch%3Dscreenshot

### Content-Type: application/json


